//
//  LoginPresenter.swift
//  DesafioAppBank
//
//  Created by jplima on 09/01/21.
//  Copyright (c) 2021 jplima. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol LoginPresentationLogic {
    func presentDetails(response: Login.UserLogin.Response)
    func presentError(message: String)
    func formatarAlgo(response: String)
}

class LoginPresenter: LoginPresentationLogic {
    weak var viewController: LoginDisplayLogic?
    
    func presentDetails(response: Login.UserLogin.Response) {
        let viewModel = Login.UserLogin.ViewModel(userSigned: response.userSigned, userAccount: response.userAccount)
        viewController?.displayDetails(viewModel: viewModel)
    }
    func presentError(message: String) {
        viewController?.displayError(message: message)
    }
    func formatarAlgo(response: String) {
        let viewModel = response + "!!"
        viewController?.displayarInformacaoNaTela(viewModel: viewModel)
    }
}
