//
//  DetailsWorker.swift
//  DesafioAppBank
//
//  Created by jplima on 09/01/21.
//  Copyright (c) 2021 jplima. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

class DetailsWorker {
    func fetchStatements(idUser: String, completion: @escaping(Result<StatementList, Error>) -> Void) {
        guard let url = URL(string: Endpoints.statements + idUser )else { return }
        let task = URLSession.shared.dataTask(with: url) { (data, response, error) in
            if error == nil, let data = data {
                do {
                    
                    let statementList = try JSONDecoder().decode(StatementList.self, from: data)
                    DispatchQueue.main.async {
                        completion(.success(statementList))
                    }
                } catch {
                    DispatchQueue.main.async {
                        completion(.failure(error))
                    }
                }
            }
            else {
                DispatchQueue.main.async {
                    completion(.failure(error!))
                }
            }
            
        }
        task.resume()
    }
}
