//
//  DetailsPresenter.swift
//  DesafioAppBank
//
//  Created by jplima on 09/01/21.
//  Copyright (c) 2021 jplima. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol DetailsPresentationLogic {
    func presentSomething(response: Details.Something.Response)
}

class DetailsPresenter: DetailsPresentationLogic {
    weak var viewController: DetailsDisplayLogic?
    
    // MARK: Do something
    
    func presentSomething(response: Details.Something.Response) {
        let viewModel = Details.Something.ViewModel(userAccount: response.userAccount)
        viewController?.displaySomething(viewModel: viewModel)
    }
}
